<a href="https://colab.research.google.com/github/programacaodinamica/dicas-pandas/blob/master/Dica_de_Pandas_Rolling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import numpy as np
import random

In [66]:
data = []
date_range = pd.date_range("01/01/2022", "01/07/2023")

for i in range(len(date_range)):

    sales_cash = random.randint(1, 10)
    sales_card = random.randint(1, 10)

    day_type = "Dia da Semana"

    if date_range[i].weekday()>4:
        day_type = "Final de Semana"

    data.append([str(date_range[i].date()), day_type, "Dinheiro", sales_cash])
    data.append([str(date_range[i].date()), day_type, "Cartão", sales_card])

data = pd.DataFrame(data, columns=["Data", "Tipo_Dia", "Tipo_Pagamento", "Vendas"])
data["Data"] = pd.to_datetime(data["Data"])

In [67]:
data

          Data         Tipo_Dia Tipo_Pagamento  Vendas
0   2022-01-01  Final de Semana       Dinheiro       9
1   2022-01-01  Final de Semana         Cartão       8
2   2022-01-02  Final de Semana       Dinheiro       6
3   2022-01-02  Final de Semana         Cartão       7
4   2022-01-03    Dia da Semana       Dinheiro       7
..         ...              ...            ...     ...
739 2023-01-05    Dia da Semana         Cartão       3
740 2023-01-06    Dia da Semana       Dinheiro       2
741 2023-01-06    Dia da Semana         Cartão       9
742 2023-01-07  Final de Semana       Dinheiro       5
743 2023-01-07  Final de Semana         Cartão       9

[744 rows x 4 columns]

In [68]:
data['roll_soma_win2'] = data.rolling(window=2).Vendas.sum()

In [73]:
data['roll_avg_win3'] = data.rolling(window=3).Vendas.mean()

In [81]:
data.drop('roll_max_win2d', axis=1, inplace=True)

In [74]:
data['roll_max_win2'] = data.rolling(window=2).Vendas.max()

In [83]:
data['roll_soma_win2d'] = data.rolling(window='7d', on='Data').Vendas.sum()

In [78]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Data            744 non-null    datetime64[ns]
 1   Tipo_Dia        744 non-null    object
 2   Tipo_Pagamento  744 non-null    object
 3   Vendas          744 non-null    int64
 4   roll_soma_win2  743 non-null    float64
 5   roll_avg_win3   742 non-null    float64
 6   roll_max_win2   743 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 40.8+ KB

In [84]:
data

,Data,Tipo_Dia,Tipo_Pagamento,Vendas,roll_soma_win2,roll_avg_win3,roll_max_win2,roll_soma_win2d
0,2022-01-01,Final de Semana,Dinheiro,9,NaN,NaN,NaN,9.0
1,2022-01-01,Final de Semana,Cartão,8,17.0,NaN,9.0,17.0
2,2022-01-02,Final de Semana,Dinheiro,6,14.0,7.666667,8.0,23.0
3,2022-01-02,Final de Semana,Cartão,7,13.0,7.000000,7.0,30.0
4,2022-01-03,Dia da Semana,Dinheiro,7,14.0,6.666667,7.0,37.0
...,...,...,...,...,...,...,...,...
739,2023-01-05,Dia da Semana,Cartão,3,9.0,4.333333,6.0,64.0
740,2023-01-06,Dia da Semana,Dinheiro,2,5.0,3.666667,3.0,54.0
741,2023-01-06,Dia da Semana,Cartão,9,11.0,4.666667,9.0,63.0
742,2023-01-07,Final de Semana,Dinheiro,5,14.0,5.333333,9.0,61.0
743,2023-01-07,Final de Semana,Cartão,9,14.0,7.666667,9.0,70.0